### ISSUE TITLE
sorry need clear usage explanation for newbie

### ISSUE THREAD

**Issue by navotera** [Monits/volley-requests#1]
i read this code : 

```

Rest.one("me")
    .get(User.class)
    .onSuccess(successListener)
    .onError(errorListener)
    .onCancel(cancelListener)
    .request();
```

i dont understand what succesListener is ? is it method or variable... sorry this is newbie question. thanks

**Comment by jsotuyod** [comment]
Hi @navotera and thanks for using our lib. I'm really sorry that you are struggling, but your feedback will help us write a clearer README.

As for your question, `successListener` is a standard `Response.Listener` instance, as you would normally use in Volley. Similary, `errorListener` is a standard Volley `Response.ErrorListener` instance.

Finally, `cancelListener` is the only introduction to Volley, it's an instance of our own [`ListenableRequest.CancelListener`](https://github.com/Monits/volley-requests/blob/master/volley-requests/src/main/java/com/monits/volleyrequests/network/request/ListenableRequest.java#L86-L91)

In the example, since `get()` is callled for `User.class`, `successListener` would be a `Response.Listener<User>` which will handle the data recovered from the network after deserializing the json with GSON.

Is it clearer now?

Shall you have any other doubts, let me know.

**Comment by navotera** [comment]
much appreciation for your answer... 
i read volley but i never use it i used optimusHTTP previously... which as i know based on okhttp.. 
im planning to use straightly your library since on my experience on php programming it would be alot easier to use library than standard raw package (default volley library)... 

if u may can u provide more example code to explain complete code to use your code... 
thank u so much sorry ... im newbie sir...

**Comment by jsotuyod** [comment]
Ok, so let's assume that you want to load a User by id. The url for a RESTful resource would be something like `/users/{id}`

The returned JSON could be something such as: `{"id": 43, "firstName":"Jon", "lastName":"Snow"}`

So you create your `User` object to map it accordingly:

``` java
public class User {
  // Field names match the JSON fields, but you could also use @SerializedName, see https://github.com/google/gson/blob/master/UserGuide.md#TOC-JSON-Field-Naming-Support
  private int id;
  private String firstName;
  private String lastName;

  public User() { }

  // TODO : getters, setters and your other methods here...
}
```

To use it, you would do:

``` java
public class MyActivity extends Activity {
  private RequestQueue queue;

  protected void onCreate(Bundle savedInstanceState) {
    // Setup Volley
    queue = Volley.newRequestQueue(this);

    // Setup REST
    Rest.setBaseUrl("http://path.to.your.api.com"); // TODO : Change this
  }

  // Call this from wherever you need it
  private void loadUser() {
    // Create request and setup callbacks
    Request<User> fetchOne = Rest.one("users", "43")
      .get(User.class)
      .onSuccess(new Response.Listener<User>() {
       @Override
        public void onResponse(User response) {
          // TODO : Do whatever you want with Jon Snow!
        }
      })
      .onError(new Response.ErrorListener() {
        @Override
        public void onErrorResponse(VolleyError error) {
          // TODO : Show error to user in a friendly way / allow  for retry?
          Toast.makeText(MyActivity.this, "The night is dark and full of terrors", Toast.LENGTH_SHORT).show();
        }
      })
      .request();

    // Actually dispatch the request
    queue.add(fetchOne);
  }
}
```

For basic Volley background, I strongly recommend you read [this](https://developer.android.com/training/volley/simple.html)

**Comment by navotera** [comment]
thanks u so much sir, seems like those likely is good if paste in volley-request read me... to help user to more concise to understand this library such as someone like me... 

Good day sir
